apiVersion: v1
kind: Secret
metadata:
  name: sc-azuredocsdbconnection-secret
  namespace: azuredocs-app
type: Opaque
stringData:
  AZURE_POSTGRESQL_CLIENTID: "PLACEHOLDER"
  AZURE_POSTGRESQL_CONNECTIONSTRING: "dbname=azuredocs host=linuxfirstdocs-db.postgres.database.azure.com port=5432 sslmode=require user=aad_azuredocs_db_connection"
