apiVersion: v1
kind: Secret
metadata:
  name: sc-azuredocsdbconnection-secret
  namespace: azuredocs-app
type: Opaque
stringData:
  AZURE_POSTGRESQL_CLIENTID: "a1e3977e-3def-4e89-97a0-a4c5dcf9158b"
  AZURE_POSTGRESQL_CONNECTIONSTRING: "dbname=azuredocs host=linuxfirstdocs-pgsql.postgres.database.azure.com port=5432 sslmode=require user=aad_azuredocs_db_connection"
