# Enable OpenTelemetry tracing for webui in dev environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: azuredocs-app
spec:
  template:
    spec:
      containers:
        - name: webui
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger.azuredocs-app.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "azuredocs-webui"
